# Generated by Django 2.0.2 on 2018-02-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180205_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='nickname',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=50, verbose_name='이름'),
        ),
    ]
